[build]
  command = "DATABASE_URL=$MIGRATION_DATABASE_URL npx prisma migrate deploy && npx prisma generate && npm run build"
  publish = "public"
  functions = "netlify/functions"

[dev]
  command = "remix watch"
  port = 3000

# Database configuration 
# Make sure you have set the following environment variables in the Netlify UI:
# - DATABASE_URL: Your regular database connection string for application use
# - MIGRATION_DATABASE_URL: Your migration-specific database connection string (if different)
[build.environment]
  NODE_VERSION = "18"
  # The following ensures Prisma can connect to your database in production
  DATABASE_URL = ""  # This will be overridden by the Netlify environment variable with the same name

# Ensure redirects work correctly
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

[[headers]]
  for = "/build/*"
  [headers.values]
    "Cache-Control" = "public, max-age=31536000, s-maxage=31536000" 