[build]
  command = "npx prisma migrate deploy && npx prisma generate && npm run build"
  publish = "public"
  functions = "netlify/functions"

[dev]
  command = "remix watch"
  port = 3000

# Add a post-processing step to run migrations
[build.environment]
  NODE_VERSION = "18"

# Ensure redirects work correctly
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

[[headers]]
  for = "/build/*"
  [headers.values]
    "Cache-Control" = "public, max-age=31536000, s-maxage=31536000" 